# Site settings
title: Sree Harsha Mamilla
url: https://mavharsha.github.io
description: " Curious, Code, Click "
github: https://github.com/mavharsha
flickr: https://secure.flickr.com/photos/76302043@N07/


# Build settings
markdown: kramdown
permalink: pretty
version: 0.0.1

