# Site settings
title: Sree Harsha Mamilla
url: https://mavharsha.github.io
description: "Curious, Coder & Photographer "


# Build settings
markdown: kramdown
permalink: pretty
version: 0.0.2

resume: /public/SreeHarsha_Resume.pdf
github: https://github.com/mavharsha
linkedin: https://www.linkedin.com/in/sreeharsham
flickr: https://secure.flickr.com/photos/76302043@N07/


