# Site settings
title: Sree Harsha Mamilla
url: https://mavharsha.github.io
description: "Curious, Coder & Photographer "


# Build settings
markdown: kramdown
permalink: pretty
version: 0.0.4

resume: /public/SreeHarsha_Mamilla.pdf
github: https://github.com/mavharsha
linkedin: https://www.linkedin.com/in/sreehm/
flickr: https://secure.flickr.com/photos/76302043@N07/
medium: https://medium.com/@_mavharsha
twitter: https://twitter.com/mavharsha


